name: Push to Gitlab CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger gitlab pipeline
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        result=$(curl -X POST \
                      -F token=$GITLAB_TOKEN \
                      -F "ref=master" \
                      -F "variables[DIST_SHA1]=$GITHUB_SHA" \
                      -F "variables[DIST_BRANCH]=$GITHUB_REF" \
                      -F "variables[DIST_REPOSITORY]=$GITHUB_REPOSITORY" \
                      -F "variables[DIST_REF]=$GITHUB_REF" \
                      -F "variables[DIST_HEAD_REF]=$GITHUB_HEAD_REF" \
                      -F "variables[DIST_BASE_REF]=$GITHUB_BASE_REF" \
                      https://gitlab.freedesktop.org/api/v4/projects/4303/trigger/pipeline)
        PIPELINE_URL=$(echo $result | jq .web_url)
        curl -X POST \
             -H "Content-Type: application/json" \
             -H "Authorization: token $GITHUB_TOKEN" \
             -d "{ \
                  \"state\": \"pending\", \
                  \"target_url\": ${PIPELINE_URL}, \
                  \"description\": \"Run pytest\", \
                  \"context\": \"Gitlab CI\" \
                }" \
             https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA
